import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  outputFileTracingIncludes: {
    "/api//\\[\\[\\.\\.\\.query\\]\\]": ["./node_modules/**/*.wasm"],
    "/api//\\[\\[\\.\\.\\.query\\]\\]/*": ["./node_modules/**/*.wasm"],
    "/api/\\[\\.\\.\\.query\\]": ["./node_modules/**/*.wasm"],
    "/api/\\[\\.\\.\\.query\\]/*": ["./node_modules/**/*.wasm"],
    "/api/\\[query\\]": ["./node_modules/**/*.wasm"],
    "/api/\\[query\\]/*": ["./node_modules/**/*.wasm"],
    "/api/*": ["./node_modules/**/*.wasm"],
    "/api/**": ["./node_modules/**/*.wasm"],
    "/api/**/*": ["./node_modules/**/*.wasm"],
    "/api/playing_with_neon/*": ["./node_modules/**/*.wasm"],
    "/api/playing_with_neon": ["./node_modules/**/*.wasm"],
    "/app/api//\\[\\[\\.\\.\\.query\\]\\]": ["./node_modules/**/*.wasm"],
    "/app/api//\\[\\[\\.\\.\\.query\\]\\]/*": ["./node_modules/**/*.wasm"],
    "/app/api/\\[\\.\\.\\.query\\]": ["./node_modules/**/*.wasm"],
    "/app/api/\\[\\.\\.\\.query\\]/*": ["./node_modules/**/*.wasm"],
    "/app/api/\\[query\\]": ["./node_modules/**/*.wasm"],
    "/app/api/\\[query\\]/*": ["./node_modules/**/*.wasm"],
    "/app/api/*": ["./node_modules/**/*.wasm"],
    "/app/api/**": ["./node_modules/**/*.wasm"],
    "/app/api/**/*": ["./node_modules/**/*.wasm"],
    "/app/api/playing_with_neon": ["./node_modules/**/*.wasm"],
    "/app/api/playing_with_neon/*": ["./node_modules/**/*.wasm"],
    "/src/app/api//\\[\\[\\.\\.\\.query\\]\\]": ["./node_modules/**/*.wasm"],
    "/src/app/api//\\[\\[\\.\\.\\.query\\]\\]/*": ["./node_modules/**/*.wasm"],
    "/src/app/api/\\[\\.\\.\\.query\\]": ["./node_modules/**/*.wasm"],
    "/src/app/api/\\[\\.\\.\\.query\\]/*": ["./node_modules/**/*.wasm"],
    "/src/app/api/\\[query\\]": ["./node_modules/**/*.wasm"],
    "/src/app/api/\\[query\\]/*": ["./node_modules/**/*.wasm"],
    "/src/app/api/*": ["./node_modules/**/*.wasm"],
    "/src/app/api/**": ["./node_modules/**/*.wasm"],
    "/src/app/api/**/*": ["./node_modules/**/*.wasm"],
    "/src/app/api/playing_with_neon/*": ["./node_modules/**/*.wasm"],
  },
};

export default nextConfig;
